site_name: Pensamentos e ExperiÃªncias
site_url: https://teoberto.com/
repo_url: https://github.com/teoberto/escritos
repo_name: teoberto/escritos

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - ğŸ  Home: index.md
  - ğŸŒ PÃºblico:
    - Artigos: publico/artigos.md
  - ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦ FamÃ­lia:
    - DiÃ¡rio: familia/teste.md